### ISSUE TITLE
Code share request

### ISSUE THREAD

**Issue by ian612** [stwlam/module-art-tools#1]
I'm working on a module for the Starfinder Foundry System to help with automating the mapping of compendium art. Would you be alright if I use/modify your csv-to-json code in it (with credit, obviously)? It'll be public release and MIT licensed, [this'll be the repo](https://github.com/ian612/sfrpg-art-map/).

Thanks!
- Ian

**Comment by stwlam** [comment]
Yes, feel free to distribute with the MIT license.
